# Generated by Django 3.1.2 on 2021-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210219_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(related_name='teachers', to='school.Student'),
        ),
    ]
