# примеры API-запросов

# получение объявлений
GET http://localhost:8000/api/advertisements?order=date
Content-Type: application/json

###
# создание объявления
POST http://localhost:8000/api/advertisements/
Content-Type: application/json
Authorization: Token aeae7afa8a26589fe5eb9d084447729431607b6e

{
  "title": "Шкаф IKEA-2",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH http://localhost:8000/api/advertisements/74/
Content-Type: application/json
Authorization: Token aeae7afa8a26589fe5eb9d084447729431607b6e

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET http://localhost:8000/api/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET http://localhost:8000/api/advertisements/?created_at-after=2021-03-01?
Content-Type: application/json

###
